#!/usr/bin/env bash
# Generate a docker-compose file describing a StarRocks cluster with
# ${FE_COUNT} FE nodes and ${BE_COUNT} BE nodes.
#
# Reads configuration from environment variables (sourced from .env by deploy.sh):
#   STARROCKS_VERSION, CLUSTER_NAME, FE_COUNT, BE_COUNT,
#   FE_QUERY_PORT, FE_HTTP_PORT
#
# Writes the resulting compose YAML to stdout.

set -euo pipefail

: "${STARROCKS_VERSION:?STARROCKS_VERSION is required}"
: "${CLUSTER_NAME:?CLUSTER_NAME is required}"
: "${FE_COUNT:?FE_COUNT is required}"
: "${BE_COUNT:?BE_COUNT is required}"
: "${FE_QUERY_PORT:?FE_QUERY_PORT is required}"
: "${FE_HTTP_PORT:?FE_HTTP_PORT is required}"

if ! [[ "$FE_COUNT" =~ ^[0-9]+$ ]] || [ "$FE_COUNT" -lt 1 ]; then
    echo "FE_COUNT must be a positive integer, got: $FE_COUNT" >&2
    exit 1
fi
if ! [[ "$BE_COUNT" =~ ^[0-9]+$ ]] || [ "$BE_COUNT" -lt 1 ]; then
    echo "BE_COUNT must be a positive integer, got: $BE_COUNT" >&2
    exit 1
fi
if [ $((FE_COUNT % 2)) -eq 0 ]; then
    echo "warning: FE_COUNT=$FE_COUNT is even. Odd values (1, 3, 5) are recommended for quorum." >&2
fi

leader="${CLUSTER_NAME}-fe-0"

cat <<HEADER
# Auto-generated by scripts/gen-multi-node.sh — do not edit by hand.
# Cluster: ${CLUSTER_NAME}  FE=${FE_COUNT}  BE=${BE_COUNT}  version=${STARROCKS_VERSION}

services:
HEADER

for i in $(seq 0 $((FE_COUNT - 1))); do
    name="${CLUSTER_NAME}-fe-${i}"
    cat <<FE
  fe-${i}:
    image: starrocks/fe-ubuntu:${STARROCKS_VERSION}
    container_name: ${name}
    hostname: ${name}
    restart: unless-stopped
    environment:
      HOST_TYPE: FQDN
      CONFIGMAP_MOUNT_PATH: /etc/starrocks/conf
      LOG_CONSOLE: "1"
    volumes:
      - ../conf:/etc/starrocks/conf:ro
      - fe_${i}_meta:/opt/starrocks/fe/meta
      - fe_${i}_log:/opt/starrocks/fe/log
FE
    if [ "$i" -eq 0 ]; then
        cat <<FEPORT
    ports:
      - "${FE_QUERY_PORT}:9030"
      - "${FE_HTTP_PORT}:8030"
FEPORT
    fi
    cat <<FEEND
    command: ["/opt/starrocks/fe_entrypoint.sh", "${leader}"]
    networks:
      - sr_net
    healthcheck:
      test: ["CMD-SHELL", "mysql --connect-timeout 2 -h 127.0.0.1 -P 9030 -u root -e 'show frontends' >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
FEEND
done

for i in $(seq 0 $((BE_COUNT - 1))); do
    name="${CLUSTER_NAME}-be-${i}"
    cat <<BE
  be-${i}:
    image: starrocks/be-ubuntu:${STARROCKS_VERSION}
    container_name: ${name}
    hostname: ${name}
    restart: unless-stopped
    depends_on:
      fe-0:
        condition: service_healthy
    environment:
      HOST_TYPE: FQDN
      CONFIGMAP_MOUNT_PATH: /etc/starrocks/conf
    volumes:
      - ../conf:/etc/starrocks/conf:ro
      - be_${i}_storage:/opt/starrocks/be/storage
      - be_${i}_log:/opt/starrocks/be/log
    command: ["/opt/starrocks/be_entrypoint.sh", "${leader}"]
    networks:
      - sr_net
BE
done

cat <<TAIL

volumes:
TAIL
for i in $(seq 0 $((FE_COUNT - 1))); do
    echo "  fe_${i}_meta:"
    echo "  fe_${i}_log:"
done
for i in $(seq 0 $((BE_COUNT - 1))); do
    echo "  be_${i}_storage:"
    echo "  be_${i}_log:"
done

cat <<NET

networks:
  sr_net:
    name: ${CLUSTER_NAME}_net
NET
