#!/usr/bin/env bash
# Render a docker-compose file for a StarRocks cluster with ${FE_COUNT} FE
# nodes and ${BE_COUNT} BE nodes. Each container uses the configured BASE_IMAGE
# directly (no docker build), with ./runtime-shared mounted read-only as the
# StarRocks software root and per-container private bind mounts for
# meta / log / storage.
#
# Reads from env (sourced from .env by deploy.sh):
#   BASE_IMAGE, CLUSTER_NAME, FE_COUNT, BE_COUNT, FE_QUERY_PORT, FE_HTTP_PORT
# Writes the resulting compose YAML to stdout.

set -euo pipefail

: "${BASE_IMAGE:?BASE_IMAGE is required}"
: "${CLUSTER_NAME:?CLUSTER_NAME is required}"
: "${FE_COUNT:?FE_COUNT is required}"
: "${BE_COUNT:?BE_COUNT is required}"
: "${FE_QUERY_PORT:?FE_QUERY_PORT is required}"
: "${FE_HTTP_PORT:?FE_HTTP_PORT is required}"

if ! [[ "$FE_COUNT" =~ ^[0-9]+$ ]] || [ "$FE_COUNT" -lt 1 ]; then
    echo "FE_COUNT must be a positive integer, got: $FE_COUNT" >&2; exit 1
fi
if ! [[ "$BE_COUNT" =~ ^[0-9]+$ ]] || [ "$BE_COUNT" -lt 1 ]; then
    echo "BE_COUNT must be a positive integer, got: $BE_COUNT" >&2; exit 1
fi
if [ "$FE_COUNT" -gt 1 ] && [ $((FE_COUNT % 2)) -eq 0 ]; then
    echo "warning: FE_COUNT=$FE_COUNT is even. Odd values are recommended for quorum." >&2
fi

leader="${CLUSTER_NAME}-fe-0"

# Paths are relative to the generated compose file (generated/cluster.yml),
# so "../" reaches the deployer root.
cat <<HEADER
# Auto-generated by scripts/gen-compose.sh — do not edit by hand.
# Cluster: ${CLUSTER_NAME}  FE=${FE_COUNT}  BE=${BE_COUNT}  base=${BASE_IMAGE}

services:
HEADER

for i in $(seq 0 $((FE_COUNT - 1))); do
    name="${CLUSTER_NAME}-fe-${i}"
    cat <<FE
  fe-${i}:
    image: ${BASE_IMAGE}
    container_name: ${name}
    hostname: ${name}
    restart: unless-stopped
    environment:
      LEADER_HOST: ${leader}
      HOST_TYPE: FQDN
      STARROCKS_HOME: /opt/starrocks
    entrypoint: ["/opt/sr-deployer/fe-entrypoint.sh"]
    volumes:
      - ../runtime-shared:/opt/starrocks:ro
      - ../runtime:/opt/sr-deployer:ro
      - ../conf/fe.conf:/opt/starrocks/fe/conf/fe.conf:ro
      - ../data/fe-${i}/meta:/opt/starrocks/fe/meta
      - ../data/fe-${i}/log:/opt/starrocks/fe/log
      - apt_cache:/var/cache/apt
      - apt_lists:/var/lib/apt/lists
FE
    if [ "$i" -eq 0 ]; then
        cat <<FEPORT
    ports:
      - "${FE_QUERY_PORT}:9030"
      - "${FE_HTTP_PORT}:8030"
FEPORT
    fi
    cat <<FEEND
    networks:
      - sr_net
    healthcheck:
      test: ["CMD-SHELL", "mysql --connect-timeout 2 -h 127.0.0.1 -P 9030 -u root -e 'show frontends' >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 30s
FEEND
done

for i in $(seq 0 $((BE_COUNT - 1))); do
    name="${CLUSTER_NAME}-be-${i}"
    cat <<BE
  be-${i}:
    image: ${BASE_IMAGE}
    container_name: ${name}
    hostname: ${name}
    restart: unless-stopped
    depends_on:
      fe-0:
        condition: service_healthy
    environment:
      LEADER_HOST: ${leader}
      STARROCKS_HOME: /opt/starrocks
    entrypoint: ["/opt/sr-deployer/be-entrypoint.sh"]
    volumes:
      - ../runtime-shared:/opt/starrocks:ro
      - ../runtime:/opt/sr-deployer:ro
      - ../conf/be.conf:/opt/starrocks/be/conf/be.conf:ro
      - ../data/be-${i}/storage:/opt/starrocks/be/storage
      - ../data/be-${i}/log:/opt/starrocks/be/log
      - apt_cache:/var/cache/apt
      - apt_lists:/var/lib/apt/lists
    networks:
      - sr_net
BE
done

cat <<TAIL

volumes:
  apt_cache:
  apt_lists:

networks:
  sr_net:
    name: ${CLUSTER_NAME}_net
TAIL
